---
name: 🐛 Bug Report
about: Report a bug to help us improve the action
title: '[BUG] '
labels: ['bug']
assignees: ''
---

## 🐛 Bug Description

**Brief description**: A clear and concise description of what the bug is.

## 🔄 Steps to Reproduce

1. Configure the action with: `[your configuration]`
2. Run the workflow with: `[describe trigger]`
3. Observe the error: `[describe what happens]`

## ✅ Expected Behavior

A clear description of what you expected to happen.

## ❌ Actual Behavior

A clear description of what actually happened.

## 📱 App Information

- **File type**: APK/AAB/APKS
- **File size**: (approximate)
- **Package name**: (if relevant)
- **Auto-detection used**: Yes/No

## 🔧 Action Configuration

```yaml
# Please share your action configuration (remove sensitive data)
- name: Deploy to Indus Appstore
  uses: indusappstore/appstore-release@vX.X.X
  with:
    file_path: './app-release.apk'
    file_type: 'apk'
    # ... other parameters
```

## 📋 Environment

- **GitHub Actions Runner**: ubuntu-latest/windows-latest/macos-latest
- **Action Version**: [e.g., v1.2.3]
- **Workflow Trigger**: [push/pull_request/manual/etc.]

## 📊 Logs

<details>
<summary>GitHub Actions Logs (click to expand)</summary>

```
# Please paste relevant logs here (remove sensitive information like API tokens)
# Focus on the error messages and the steps leading up to the failure
```

</details>

## 🔐 Keystore Information (if applicable)

- **Keystore source**: base64/cdn/script/encrypted_file/file/none
- **Keystore validation enabled**: Yes/No
- **Error occurs during**: keystore setup/validation/signing/upload

## 🤔 Additional Context

- Is this a regression? (worked before but now doesn't)
- Any recent changes to your workflow or app?
- Have you tried with different file types?
- Any workarounds you've discovered?

## ✅ Checklist

- [ ] I have searched existing issues for duplicates
- [ ] I have provided all required information
- [ ] I have removed sensitive information from logs and configuration
- [ ] I have tested with the latest version of the action
