# AAB deployment with base64 keystore example
# Shows how to deploy an AAB with secure keystore handling
name: Deploy AAB with Base64 Keystore

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy AAB to Indus Appstore
        uses: indusappstore/appstore-release@v1
        with:
          operation_mode: 'deploy_only'
          file_path: './app-release.aab'
          file_type: 'aab'
          api_token: ${{ secrets.INDUS_APP_STORE_API_TOKEN }}
          
          # Auto-detect package name from AAB (recommended)
          auto_detect_package: 'true'
          
          # Keystore configuration for AAB signing
          keystore_source: 'base64'
          keystore_base64: ${{ secrets.KEYSTORE_BASE64 }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          key_alias: ${{ secrets.KEY_ALIAS }}
          key_password: ${{ secrets.KEY_PASSWORD }}
          
          # Enable security validation
          keystore_validation: 'true'
